name: CI_action

on:
  push:
    branches: 
    - main

env:
  MONGODB_CONNECTION_STRING: ${{ secrets.MONGODB_CONNECTION_STRING }}
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    # - name: Checkout repository
    - uses: actions/checkout@v2
    - name: Set up Node.js '14'
      uses: actions/setup-node@v1
      with:
        node-version: '14'
    - name: Install dependencies
      run: npm install

    - name: Run the tests
      run: npm test

 
   
