name: CI_action
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Node.js v16.13.2
      uses: actions/setup-node@v1
      with:
        node-version: v16.13.2
    - name: Install dependencies
      run: npm install
    - name: Run the tests
      run: npm test
    - name: Build
      run: npm run build
